# Generated by Django 4.1 on 2022-08-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='alergenos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.alergenos'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.category'),
        ),
    ]
