# Generated by Django 4.1 on 2022-08-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_alergenos_alter_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
