# Generated by Django 4.1 on 2022-08-04 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_alergenos_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='alergenos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='menu.alergenos'),
        ),
    ]
