# Generated by Django 4.1 on 2022-08-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alergenos_created_at_alergenos_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alergenos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/alergenos_images'),
        ),
    ]
