# Generated by Django 4.1 on 2022-08-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_alergenos_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='alergenos',
        ),
        migrations.AddField(
            model_name='menu',
            name='alergenos',
            field=models.ManyToManyField(to='menu.alergenos'),
        ),
    ]
