# Generated by Django 4.1 on 2022-08-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_menu_alergenos_remove_menu_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/restaurant_logo'),
        ),
    ]
