# Generated by Django 4.1 on 2022-08-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='static/restaurants_favicon'),
        ),
    ]
