# Generated by Django 4.1 on 2022-08-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_restaurant_name_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
