# Generated by Django 4.1 on 2022-08-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_restaurant_time_restaurant_whatsaap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='whatsaap',
            new_name='whatsapp',
        ),
    ]
