# Generated by Django 4.1 on 2022-08-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_rename_whatsaap_restaurant_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
