# Generated by Django 4.1 on 2022-08-08 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='button_text1',
            new_name='button_code1',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='button_text2',
            new_name='button_code2',
        ),
    ]
