# Generated by Django 4.1 on 2022-08-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_rename_button_text1_banner_button_code1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='button_code1',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_code2',
        ),
        migrations.AddField(
            model_name='banner',
            name='button',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
