# Generated by Django 4.1 on 2022-08-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_remove_banner_button_code1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_number',
            field=models.IntegerField(default=1),
        ),
    ]
